optuna:
  monitor: valid/loss
  study:
    study_name: NOTSET
    direction: minimize
  optimize:
    n_trials: 3
    
  model:
    init_args:
      n_layers:
        type: int
        kwargs:
          low: 1
          high: 4
